# Generated by Django 5.2.3 on 2025-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="仅对 student 用户生效，用于记录学习进度",
                null=True,
            ),
        ),
    ]
