# Generated by Django 5.2.3 on 2025-06-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledges", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="knowledgepoint",
            old_name="category",
            new_name="sub_topic",
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="knowledge_area",
            field=models.CharField(
                choices=[
                    ("项目整合管理", "项目整合管理"),
                    ("项目范围管理", "项目范围管理"),
                    ("项目进度管理", "项目进度管理"),
                    ("项目成本管理", "项目成本管理"),
                    ("项目质量管理", "项目质量管理"),
                    ("项目资源管理", "项目资源管理"),
                    ("项目沟通管理", "项目沟通管理"),
                    ("项目风险管理", "项目风险管理"),
                    ("项目采购管理", "项目采购管理"),
                    ("项目相关方管理", "项目相关方管理"),
                ],
                default="项目整合管理",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
