# Generated by Django 5.2.3 on 2025-06-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("answer", models.CharField(max_length=10)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledges.knowledgepoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected", models.CharField(max_length=10)),
                ("correct", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizzes.quiz"
                    ),
                ),
            ],
        ),
    ]
