# Generated by Django 5.2.3 on 2025-06-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_remove_quiz_answer_remove_quiz_knowledge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
            ),
        ),
    ]
